# Generated by Django 4.1.7 on 2025-10-30 22:52

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_imagem_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='img',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='img', variations={'card': (320, 200, True), 'carousel': (1200, 675, True)}),
        ),
    ]
