# Generated by Django 4.1.7 on 2025-10-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_alter_imagem_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
